### ISSUE TITLE
[BUG] Registered commands do not work

### ISSUE THREAD

**Issue by Fabb111** [Pante/chimera#253]
**Describe the bug**
When trying to register a command other than the "tell" command in 1.16.4, it will not execute. I tried every possible variant, but every time the "syntax" message or no message if syntax was not defined gets displayed.

**To Reproduce**
1. Defined command with Scribe (yml generates correctly; checked it)
```kotlin
@Command(
    name = "testcommand",
    aliases = ["tcmd"]
)
```
2. Register command
```kotlin
val dispatcher = Dispatcher.of(this)
dispatcher.root.addChild(
    Literal.of("testcommand").then(Argument.of("?", IntegerArgumentType.integer(30, 43))
        .suggests { context, builder ->
            builder.suggest(42, LiteralMessage("The answer to life the universe and everything")).buildFuture()
        }).build())
dispatcher.update()
```
or
```kotlin
val dispatcher = Dispatcher.of(this)
dispatcher.root.addChild(
    Literal.of("testcommand").executes { command ->
        command.source.sendMessage("ok")
        return@executes 1
    }
dispatcher.update()
```
3. Execute command /testcommand or /tcmd
4. Nothing happens (no suggestion or execution) - when using "tell" as the command name, the examples work

**Expected behavior**
The command should execute instead of doing nothing

**Screenshots**
\-

**Environment (please complete the following information):**
 - Kotlin 1.4 (compiling to Java 11)
 - PaperSpigot (running on Java 13)
 - 1.16.4
 - 4.9.0-SNAPSHOT

**Additional context**
\-

**Comment by Fabb111** [comment]
Ok, I found out what the problem was. If the command is declared in the plugin.yml, it will not register because of this check:
```java
public DispatcherCommand register(LiteralCommandNode<CommandSender> command) {
    if (this.map.getKnownCommands().containsKey(command.getName())) {
        return null;
    } else {
        DispatcherCommand wrapped = this.wrap(command);
        this.map.register(this.prefix, wrapped);
        return wrapped;
    }
}
```
Is this intended? Maybe this should be documented

**Comment by Pante** [comment]
It is intended, the reason why we check if `map.getKnownCommands()` already contains the given command is to prevent people from accidentally overriding commands that they (or other plugins) already registered. That said, I won't recommend using scribe to register commands. 

Scribe has been slated for removal in `4.9.0` since from my understanding no one really uses, putting into question the maintenance-to-benefit ratio.  Secondly, I just no longer believe that annotations to plugin.yml is the best solution. Going forward, I probably will be writing a lint for `plugin.yml`s that potentially replaces placeholders with values from a pom.xml/other build files but I digress.

If you're interested in using annotations to register commands, I would recommend using the new `typist` project. It's a revamped & repackaged version of [creating commands with annotations](https://github.com/Pante/Chimera/wiki/creating-commands-using-annotations). It is pretty much feature complete, but we're still in the midst of testing and fine-tuning it.

Lastly, I agree that this behaviour should have been documented, thanks for highlighting it.

**Comment by Fabb111** [comment]
Thank you for your detailed explanation!
