### ISSUE TITLE
Command description

### ISSUE THREAD

**Issue by SkytAsul** [Pante/chimera#296]
**Is your feature request related to a problem? Please describe.**
There is no way to put a command description when registering a command through chimera. When using /help, the command appears with no description.

**Describe the solution you'd like**
A way to register a command description.

**Comment by Pante** [comment]
It has been on the back-burner for a long time now and kinda slipped my mind. The implementation I had in mind was to provide an additional `description` field in `Literal` and `Argument`, falling back to the usage text in the case where a `LiteralCommandNode` or `ArgumentCommandNode` is used (since Brigadier's  `CommandNode`s do not contain descriptions). Does this satisfy your use-case?

**Comment by SkytAsul** [comment]
Yes, awesome!
