### ISSUE TITLE
[BUG] Bad service configuration file, or exception thrown while constructing Processor object: com/karuslabs/utilitary/AnnotationProcessor

### ISSUE THREAD

**Issue by soshimee** [Pante/chimera#366]
**Describe the bug**
When building, it says `Bad service configuration file, or exception thrown while constructing Processor object: com/karuslabs/utilitary/AnnotationProcessor`

**To Reproduce**
1. Build with typist
2. See error

**Expected behavior**
I expected it to build, since there are no errors on my IDE.

**Environment (please complete the following information):**
 - Java Version: 17
 - Platform: Paper
 - Platform Version: 1.18.2
 - Chimera Version: 5.2.0

**Comment by Pante** [comment]
Interesting, seems like there's a configuration error in Typist 5.2.0. In hindsight, I completely forgot to bump the version when releasing 5.2.0. Reverting `typist` to 5.1.0 seems to fix it on my side. In the interim, perhaps you can downgrade to 5.1.0 while I work on a fix.

**Comment by Pante** [comment]
Thanks for reporting the issue, @soshimee ! After looking into the issue, it seems to be due to a misconfiguration in maven-shade for `typist`, specifically, we were accidentally creating separate shaded artifacts. We've seen released a fix that patches `5.2.0`. All that needs to be done is clear you local cache and rebuild the project. 

Please do let us know if the issue still persists.
