### ISSUE TITLE
Could not GET dependency metadata.xml

### ISSUE THREAD

**Issue by Demozo** [Pante/Chimera#91]
I'm using Gradle in my project, and when attempting to build I'm getting:
```
org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://repo.karuslabs.com/repository/lingua-franca-releases/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Repository version policy: RELEASE does not allow metadata in path: com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml
```

From my build.gradle
```
repositories {
    maven { url 'https://repo.karuslabs.com/repository/chimera-releases/' }
    maven { url 'https://repo.karuslabs.com/repository/lingua-franca-releases/' }
}

dependencies {
    compile group: 'com.karuslabs', name: 'commons', version: '4.2.0'
}
```

I found the `lingua-franca` repo on your server, which fixed the issue that it was unable to retrieve the dependency in the first place, however this issue still remains.

**Comment by Pante** [comment]
I'm pretty sure that's not the full `build.gradle` and there's a dependency on BukkitExecutors. What's happening is that Gradle is trying to find the BukkitExecutors repository in Chimera's and Lingua Franca's repository. That fails since it's not hosted in either repository and causes the exception.

Try removing the repository for lingua-franca unless you're using lingua-franca too. After which, add the following repositories which I took from [here](https://github.com/aadnk/BukkitExecutors/blob/master/BukkitExecutors/pom.xml#L24) your `build.gradle`.
```
repositories {
    maven { url 'https://repo.karuslabs.com/repository/chimera-releases/' }
    maven { url http://repo.comphenix.net/content/repositories/snapshots/' }
    maven { url 'http://repo.comphenix.net/content/repositories/releases/'}
    // Your other repositories
}
```
This should fix the issue, do let me know if the error still persists.

**Comment by Demozo** [comment]
Correct, that was only the relevant part of my `build.gradle` file.
Adding the repository did indeed fix my issue, thank you.
